name: fyp_pro
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^3.0.0
  flutter_local_notifications: ^18.0.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  get: ^4.6.6
  introduction_screen: ^3.1.14
  convex_bottom_bar: ^3.2.0
  intl: ^0.19.0
  hijri: ^3.0.0
  adhan: ^2.0.0+1
  location: ^7.0.1
  shared_preferences: ^2.3.2
  flutter_qiblah: ^3.0.4
  geolocator: ^13.0.1
  universal_io: ^2.2.2
  cloud_firestore: ^5.4.3
  solid_bottom_sheet: ^0.1.13
  just_audio: ^0.9.41
  font_awesome_flutter: ^10.7.0
  flutter_spinkit: ^5.2.1
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  unicons: ^3.0.0
  rxdart: ^0.28.0
  timeago: ^3.7.0
  share_plus: ^10.1.0
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_calendar: ^28.1.33
  timezone: ^0.9.0
  animations: ^2.0.11
  flutter_pdfview: ^1.3.4
  syncfusion_flutter_pdfviewer: ^28.1.33
  video_player: ^2.9.2
  open_file: ^3.5.10
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  audio_session: any
  csc_picker: any
  syncfusion_flutter_datepicker: ^28.1.33
  chewie: ^1.8.5
  firebase_messaging: ^15.1.6
  flutter_stripe: ^11.3.0
  dio: ^5.7.0
  geocoding: ^3.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16

  zego_uikit_prebuilt_call: ^4.16.11
  zego_zimkit: ^1.18.13
  firebase_crashlytics: ^4.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.0.0
  build_web_compilers: ^4.0.4
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/bgtheme.jfif
    - assets/images/theme.jfif
    - assets/images/bg.jfif
    - assets/images/collection_icon/duas.svg
    - assets/images/collection_icon/quran.svg
    - assets/images/collection_icon/prayer_time.svg
    - assets/images/collection_icon/tasbih.svg
    - assets/images/collection_icon/alim.svg
    - assets/images/collection_icon/fatwa.svg
    - assets/images/collection_icon/community.svg
    - assets/images/collection_icon/course.svg
    - assets/images/collection_icon/kiblat1.svg
    - assets/images/my.png
    - assets/images/collection_icon/holyQuran.png
    - assets/images/collection_icon/home.png
    - assets/images/collection_icon/audio.png
    - assets/images/Qiblah/kiblat_lingkar.svg
    - assets/images/Qiblah/kiblat_needle.svg
    - assets/images/bg_tasbih.jpg
    - assets/images/alims/alim1.jpeg
    - assets/images/alims/alim2.jpeg
    - assets/images/alims/alim3.jpeg
    - assets/images/alims/alim4.jpeg
    - assets/images/payments/Easypaisa.jpg
    - assets/images/payments/Jazzcash.jpg
    - assets/images/payments/visa.jpg
    - assets/images/payments/visacard.png
    - assets/images/payments/mastercard.png
    - assets/images/payments/mastercard1.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700